// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"context"

	"github.com/NpoolPlatform/basal-middleware/pkg/db/ent/api"
	"github.com/NpoolPlatform/basal-middleware/pkg/db/ent/pubsubmessage"
	"github.com/NpoolPlatform/basal-middleware/pkg/db/ent/schema"
	"github.com/google/uuid"

	"entgo.io/ent"
	"entgo.io/ent/privacy"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	apiMixin := schema.API{}.Mixin()
	api.Policy = privacy.NewPolicies(apiMixin[0], schema.API{})
	api.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := api.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	apiMixinFields0 := apiMixin[0].Fields()
	_ = apiMixinFields0
	apiFields := schema.API{}.Fields()
	_ = apiFields
	// apiDescCreatedAt is the schema descriptor for created_at field.
	apiDescCreatedAt := apiMixinFields0[0].Descriptor()
	// api.DefaultCreatedAt holds the default value on creation for the created_at field.
	api.DefaultCreatedAt = apiDescCreatedAt.Default.(func() uint32)
	// apiDescUpdatedAt is the schema descriptor for updated_at field.
	apiDescUpdatedAt := apiMixinFields0[1].Descriptor()
	// api.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	api.DefaultUpdatedAt = apiDescUpdatedAt.Default.(func() uint32)
	// api.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	api.UpdateDefaultUpdatedAt = apiDescUpdatedAt.UpdateDefault.(func() uint32)
	// apiDescDeletedAt is the schema descriptor for deleted_at field.
	apiDescDeletedAt := apiMixinFields0[2].Descriptor()
	// api.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	api.DefaultDeletedAt = apiDescDeletedAt.Default.(func() uint32)
	// apiDescProtocol is the schema descriptor for protocol field.
	apiDescProtocol := apiFields[1].Descriptor()
	// api.DefaultProtocol holds the default value on creation for the protocol field.
	api.DefaultProtocol = apiDescProtocol.Default.(string)
	// apiDescServiceName is the schema descriptor for service_name field.
	apiDescServiceName := apiFields[2].Descriptor()
	// api.DefaultServiceName holds the default value on creation for the service_name field.
	api.DefaultServiceName = apiDescServiceName.Default.(string)
	// apiDescMethod is the schema descriptor for method field.
	apiDescMethod := apiFields[3].Descriptor()
	// api.DefaultMethod holds the default value on creation for the method field.
	api.DefaultMethod = apiDescMethod.Default.(string)
	// apiDescMethodName is the schema descriptor for method_name field.
	apiDescMethodName := apiFields[4].Descriptor()
	// api.DefaultMethodName holds the default value on creation for the method_name field.
	api.DefaultMethodName = apiDescMethodName.Default.(string)
	// apiDescPath is the schema descriptor for path field.
	apiDescPath := apiFields[5].Descriptor()
	// api.DefaultPath holds the default value on creation for the path field.
	api.DefaultPath = apiDescPath.Default.(string)
	// apiDescExported is the schema descriptor for exported field.
	apiDescExported := apiFields[6].Descriptor()
	// api.DefaultExported holds the default value on creation for the exported field.
	api.DefaultExported = apiDescExported.Default.(bool)
	// apiDescPathPrefix is the schema descriptor for path_prefix field.
	apiDescPathPrefix := apiFields[7].Descriptor()
	// api.DefaultPathPrefix holds the default value on creation for the path_prefix field.
	api.DefaultPathPrefix = apiDescPathPrefix.Default.(string)
	// apiDescDomains is the schema descriptor for domains field.
	apiDescDomains := apiFields[8].Descriptor()
	// api.DefaultDomains holds the default value on creation for the domains field.
	api.DefaultDomains = apiDescDomains.Default.([]string)
	// apiDescDepracated is the schema descriptor for depracated field.
	apiDescDepracated := apiFields[9].Descriptor()
	// api.DefaultDepracated holds the default value on creation for the depracated field.
	api.DefaultDepracated = apiDescDepracated.Default.(bool)
	// apiDescID is the schema descriptor for id field.
	apiDescID := apiFields[0].Descriptor()
	// api.DefaultID holds the default value on creation for the id field.
	api.DefaultID = apiDescID.Default.(func() uuid.UUID)
	pubsubmessageMixin := schema.PubsubMessage{}.Mixin()
	pubsubmessage.Policy = privacy.NewPolicies(pubsubmessageMixin[0], schema.PubsubMessage{})
	pubsubmessage.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := pubsubmessage.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	pubsubmessageMixinFields0 := pubsubmessageMixin[0].Fields()
	_ = pubsubmessageMixinFields0
	pubsubmessageFields := schema.PubsubMessage{}.Fields()
	_ = pubsubmessageFields
	// pubsubmessageDescCreatedAt is the schema descriptor for created_at field.
	pubsubmessageDescCreatedAt := pubsubmessageMixinFields0[0].Descriptor()
	// pubsubmessage.DefaultCreatedAt holds the default value on creation for the created_at field.
	pubsubmessage.DefaultCreatedAt = pubsubmessageDescCreatedAt.Default.(func() uint32)
	// pubsubmessageDescUpdatedAt is the schema descriptor for updated_at field.
	pubsubmessageDescUpdatedAt := pubsubmessageMixinFields0[1].Descriptor()
	// pubsubmessage.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	pubsubmessage.DefaultUpdatedAt = pubsubmessageDescUpdatedAt.Default.(func() uint32)
	// pubsubmessage.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	pubsubmessage.UpdateDefaultUpdatedAt = pubsubmessageDescUpdatedAt.UpdateDefault.(func() uint32)
	// pubsubmessageDescDeletedAt is the schema descriptor for deleted_at field.
	pubsubmessageDescDeletedAt := pubsubmessageMixinFields0[2].Descriptor()
	// pubsubmessage.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	pubsubmessage.DefaultDeletedAt = pubsubmessageDescDeletedAt.Default.(func() uint32)
	// pubsubmessageDescMessageID is the schema descriptor for message_id field.
	pubsubmessageDescMessageID := pubsubmessageFields[1].Descriptor()
	// pubsubmessage.DefaultMessageID holds the default value on creation for the message_id field.
	pubsubmessage.DefaultMessageID = pubsubmessageDescMessageID.Default.(string)
	// pubsubmessageDescState is the schema descriptor for state field.
	pubsubmessageDescState := pubsubmessageFields[2].Descriptor()
	// pubsubmessage.DefaultState holds the default value on creation for the state field.
	pubsubmessage.DefaultState = pubsubmessageDescState.Default.(string)
	// pubsubmessageDescRespToID is the schema descriptor for resp_to_id field.
	pubsubmessageDescRespToID := pubsubmessageFields[3].Descriptor()
	// pubsubmessage.DefaultRespToID holds the default value on creation for the resp_to_id field.
	pubsubmessage.DefaultRespToID = pubsubmessageDescRespToID.Default.(func() uuid.UUID)
	// pubsubmessageDescUndoID is the schema descriptor for undo_id field.
	pubsubmessageDescUndoID := pubsubmessageFields[4].Descriptor()
	// pubsubmessage.DefaultUndoID holds the default value on creation for the undo_id field.
	pubsubmessage.DefaultUndoID = pubsubmessageDescUndoID.Default.(func() uuid.UUID)
	// pubsubmessageDescArguments is the schema descriptor for arguments field.
	pubsubmessageDescArguments := pubsubmessageFields[5].Descriptor()
	// pubsubmessage.DefaultArguments holds the default value on creation for the arguments field.
	pubsubmessage.DefaultArguments = pubsubmessageDescArguments.Default.(string)
}

const (
	Version = "v0.11.2"                                         // Version of ent codegen.
	Sum     = "h1:UM2/BUhF2FfsxPHRxLjQbhqJNaDdVlOwNIAMLs2jyto=" // Sum of ent codegen.
)
