// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/NpoolPlatform/basal-middleware/pkg/db/ent/api"
	"github.com/NpoolPlatform/basal-middleware/pkg/db/ent/pubsubmessage"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entql"
	"entgo.io/ent/schema/field"
)

// schemaGraph holds a representation of ent/schema at runtime.
var schemaGraph = func() *sqlgraph.Schema {
	graph := &sqlgraph.Schema{Nodes: make([]*sqlgraph.Node, 2)}
	graph.Nodes[0] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   api.Table,
			Columns: api.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: api.FieldID,
			},
		},
		Type: "API",
		Fields: map[string]*sqlgraph.FieldSpec{
			api.FieldCreatedAt:   {Type: field.TypeUint32, Column: api.FieldCreatedAt},
			api.FieldUpdatedAt:   {Type: field.TypeUint32, Column: api.FieldUpdatedAt},
			api.FieldDeletedAt:   {Type: field.TypeUint32, Column: api.FieldDeletedAt},
			api.FieldEntID:       {Type: field.TypeUUID, Column: api.FieldEntID},
			api.FieldProtocol:    {Type: field.TypeString, Column: api.FieldProtocol},
			api.FieldServiceName: {Type: field.TypeString, Column: api.FieldServiceName},
			api.FieldMethod:      {Type: field.TypeString, Column: api.FieldMethod},
			api.FieldMethodName:  {Type: field.TypeString, Column: api.FieldMethodName},
			api.FieldPath:        {Type: field.TypeString, Column: api.FieldPath},
			api.FieldExported:    {Type: field.TypeBool, Column: api.FieldExported},
			api.FieldPathPrefix:  {Type: field.TypeString, Column: api.FieldPathPrefix},
			api.FieldDomains:     {Type: field.TypeJSON, Column: api.FieldDomains},
			api.FieldDeprecated:  {Type: field.TypeBool, Column: api.FieldDeprecated},
		},
	}
	graph.Nodes[1] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   pubsubmessage.Table,
			Columns: pubsubmessage.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: pubsubmessage.FieldID,
			},
		},
		Type: "PubsubMessage",
		Fields: map[string]*sqlgraph.FieldSpec{
			pubsubmessage.FieldCreatedAt: {Type: field.TypeUint32, Column: pubsubmessage.FieldCreatedAt},
			pubsubmessage.FieldUpdatedAt: {Type: field.TypeUint32, Column: pubsubmessage.FieldUpdatedAt},
			pubsubmessage.FieldDeletedAt: {Type: field.TypeUint32, Column: pubsubmessage.FieldDeletedAt},
			pubsubmessage.FieldMessageID: {Type: field.TypeString, Column: pubsubmessage.FieldMessageID},
			pubsubmessage.FieldState:     {Type: field.TypeString, Column: pubsubmessage.FieldState},
			pubsubmessage.FieldRespToID:  {Type: field.TypeUUID, Column: pubsubmessage.FieldRespToID},
			pubsubmessage.FieldUndoID:    {Type: field.TypeUUID, Column: pubsubmessage.FieldUndoID},
			pubsubmessage.FieldArguments: {Type: field.TypeString, Column: pubsubmessage.FieldArguments},
			pubsubmessage.FieldEntID:     {Type: field.TypeUUID, Column: pubsubmessage.FieldEntID},
		},
	}
	return graph
}()

// predicateAdder wraps the addPredicate method.
// All update, update-one and query builders implement this interface.
type predicateAdder interface {
	addPredicate(func(s *sql.Selector))
}

// addPredicate implements the predicateAdder interface.
func (aq *APIQuery) addPredicate(pred func(s *sql.Selector)) {
	aq.predicates = append(aq.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the APIQuery builder.
func (aq *APIQuery) Filter() *APIFilter {
	return &APIFilter{config: aq.config, predicateAdder: aq}
}

// addPredicate implements the predicateAdder interface.
func (m *APIMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the APIMutation builder.
func (m *APIMutation) Filter() *APIFilter {
	return &APIFilter{config: m.config, predicateAdder: m}
}

// APIFilter provides a generic filtering capability at runtime for APIQuery.
type APIFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *APIFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[0].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql int predicate on the id field.
func (f *APIFilter) WhereID(p entql.IntP) {
	f.Where(p.Field(api.FieldID))
}

// WhereCreatedAt applies the entql uint32 predicate on the created_at field.
func (f *APIFilter) WhereCreatedAt(p entql.Uint32P) {
	f.Where(p.Field(api.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql uint32 predicate on the updated_at field.
func (f *APIFilter) WhereUpdatedAt(p entql.Uint32P) {
	f.Where(p.Field(api.FieldUpdatedAt))
}

// WhereDeletedAt applies the entql uint32 predicate on the deleted_at field.
func (f *APIFilter) WhereDeletedAt(p entql.Uint32P) {
	f.Where(p.Field(api.FieldDeletedAt))
}

// WhereEntID applies the entql [16]byte predicate on the ent_id field.
func (f *APIFilter) WhereEntID(p entql.ValueP) {
	f.Where(p.Field(api.FieldEntID))
}

// WhereProtocol applies the entql string predicate on the protocol field.
func (f *APIFilter) WhereProtocol(p entql.StringP) {
	f.Where(p.Field(api.FieldProtocol))
}

// WhereServiceName applies the entql string predicate on the service_name field.
func (f *APIFilter) WhereServiceName(p entql.StringP) {
	f.Where(p.Field(api.FieldServiceName))
}

// WhereMethod applies the entql string predicate on the method field.
func (f *APIFilter) WhereMethod(p entql.StringP) {
	f.Where(p.Field(api.FieldMethod))
}

// WhereMethodName applies the entql string predicate on the method_name field.
func (f *APIFilter) WhereMethodName(p entql.StringP) {
	f.Where(p.Field(api.FieldMethodName))
}

// WherePath applies the entql string predicate on the path field.
func (f *APIFilter) WherePath(p entql.StringP) {
	f.Where(p.Field(api.FieldPath))
}

// WhereExported applies the entql bool predicate on the exported field.
func (f *APIFilter) WhereExported(p entql.BoolP) {
	f.Where(p.Field(api.FieldExported))
}

// WherePathPrefix applies the entql string predicate on the path_prefix field.
func (f *APIFilter) WherePathPrefix(p entql.StringP) {
	f.Where(p.Field(api.FieldPathPrefix))
}

// WhereDomains applies the entql json.RawMessage predicate on the domains field.
func (f *APIFilter) WhereDomains(p entql.BytesP) {
	f.Where(p.Field(api.FieldDomains))
}

// WhereDeprecated applies the entql bool predicate on the deprecated field.
func (f *APIFilter) WhereDeprecated(p entql.BoolP) {
	f.Where(p.Field(api.FieldDeprecated))
}

// addPredicate implements the predicateAdder interface.
func (pmq *PubsubMessageQuery) addPredicate(pred func(s *sql.Selector)) {
	pmq.predicates = append(pmq.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the PubsubMessageQuery builder.
func (pmq *PubsubMessageQuery) Filter() *PubsubMessageFilter {
	return &PubsubMessageFilter{config: pmq.config, predicateAdder: pmq}
}

// addPredicate implements the predicateAdder interface.
func (m *PubsubMessageMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the PubsubMessageMutation builder.
func (m *PubsubMessageMutation) Filter() *PubsubMessageFilter {
	return &PubsubMessageFilter{config: m.config, predicateAdder: m}
}

// PubsubMessageFilter provides a generic filtering capability at runtime for PubsubMessageQuery.
type PubsubMessageFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *PubsubMessageFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[1].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql int predicate on the id field.
func (f *PubsubMessageFilter) WhereID(p entql.IntP) {
	f.Where(p.Field(pubsubmessage.FieldID))
}

// WhereCreatedAt applies the entql uint32 predicate on the created_at field.
func (f *PubsubMessageFilter) WhereCreatedAt(p entql.Uint32P) {
	f.Where(p.Field(pubsubmessage.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql uint32 predicate on the updated_at field.
func (f *PubsubMessageFilter) WhereUpdatedAt(p entql.Uint32P) {
	f.Where(p.Field(pubsubmessage.FieldUpdatedAt))
}

// WhereDeletedAt applies the entql uint32 predicate on the deleted_at field.
func (f *PubsubMessageFilter) WhereDeletedAt(p entql.Uint32P) {
	f.Where(p.Field(pubsubmessage.FieldDeletedAt))
}

// WhereMessageID applies the entql string predicate on the message_id field.
func (f *PubsubMessageFilter) WhereMessageID(p entql.StringP) {
	f.Where(p.Field(pubsubmessage.FieldMessageID))
}

// WhereState applies the entql string predicate on the state field.
func (f *PubsubMessageFilter) WhereState(p entql.StringP) {
	f.Where(p.Field(pubsubmessage.FieldState))
}

// WhereRespToID applies the entql [16]byte predicate on the resp_to_id field.
func (f *PubsubMessageFilter) WhereRespToID(p entql.ValueP) {
	f.Where(p.Field(pubsubmessage.FieldRespToID))
}

// WhereUndoID applies the entql [16]byte predicate on the undo_id field.
func (f *PubsubMessageFilter) WhereUndoID(p entql.ValueP) {
	f.Where(p.Field(pubsubmessage.FieldUndoID))
}

// WhereArguments applies the entql string predicate on the arguments field.
func (f *PubsubMessageFilter) WhereArguments(p entql.StringP) {
	f.Where(p.Field(pubsubmessage.FieldArguments))
}

// WhereEntID applies the entql [16]byte predicate on the ent_id field.
func (f *PubsubMessageFilter) WhereEntID(p entql.ValueP) {
	f.Where(p.Field(pubsubmessage.FieldEntID))
}
